version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: master
    ignore:
      - dependency-name: org.apache.maven:*
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /docker/backup
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /docker/database
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /docker/server
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /docker/website
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
