version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: master
    ignore:
      - dependency-name: org.apache.maven:*
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    target-branch: master
    labels:
      - dependencies
