version: '3'

### Ports
# gse-db: 3306 (mysql default port)
# gse-fe: listening to 3030 (see default.conf file)
# gse-app: listening to 8080



services:
  gse-db:
    image: mysql:8.0.22
    container_name: gse-db
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 9ijn8uhb7ygv
      MYSQL_DATABASE: gse
      MYSQL_USER: gseadmin
      MYSQL_PASSWORD: Lugano2020
      TZ: UTC

  gse-fe:
#    build:
#      context: ./
#      dockerfile: Dockerfile.fe
    image: 'gitlab.reveal.si.usi.ch:60090/students/2020/ozren-dabic/github-search-engine/frontend'
    container_name: gse-fe
    restart: on-failure:5
    labels:
      - traefik.http.routers.gse-fe.rule=Host(`seart-ghs.si.usi.ch`)
      - traefik.http.services.gse-fe-service.loadbalancer.server.port=3030
      - traefik.docker.network=reverseproxy-network
    volumes:
      - ./nginx-gse-fe/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./nginx-gse-fe/default.conf.template:/etc/nginx/conf.d/default.conf.template
#    ports:
      # temporarily for STRIPE project
      #- "7030:3030"
    depends_on:
      - gse-app
    networks:
      - default
      - reverseproxy


  gse-app:
#    build:
#       context: ./
#       dockerfile: Dockerfile.be
    image: 'gitlab.reveal.si.usi.ch:60090/students/2020/ozren-dabic/github-search-engine/backend'
    container_name: gse-app
    restart: on-failure:5
    environment:
      WAIT_HOSTS: gse-db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://gse-db:3306/gse?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
      SPRING_FLYWAY__URL: jdbc:mysql://gse-db:3306/gse?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
    depends_on:
      - gse-db


networks:
  default:
    name: gse-network
  reverseproxy:
    external:
      name: reverseproxy-network
