version: '3.9'
name: 'gse'

services:

  gse-db:
    image: mysql:8.0.33
    container_name: gse-db
    restart: "always"
    volumes:
      - data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: gse
      MYSQL_USER: gseadmin
      MYSQL_PASSWORD: Lugano2020
      TZ: UTC
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  gse-migration:
    image: flyway/flyway:9.21.1-alpine
    container_name: gse-migrations
    restart: "no"
    volumes:
      - ../flyway/sql:/flyway/sql
    environment:
      TZ: UTC
      FLYWAY_USER: gseadmin
      FLYWAY_PASSWORD: Lugano2020
      FLYWAY_URL: jdbc:mysql://gse-db:3306/gse?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      FLYWAY_SCHEMAS: gse
      FLYWAY_DEFAULT_SCHEMA: gse
    command: migrate
    depends_on:
      gse-db:
        condition: service_healthy
    networks:
      - default

  gse-backup:
    image: tiredofit/db-backup:3.9.6
    container_name: gse-backup
    restart: "no"
    volumes:
      - backup:/backup
      - ./bkpdb:/assets/scripts/post
    environment:
      TZ: UTC
      TIMEZONE: Etc/UTC
      DB_TYPE: mysql
      DB_HOST: gse-db
      DB_NAME: gse
      DB_USER: gseadmin
      DB_PASS: Lugano2020
      DB_DUMP_FREQ: "1440"
      DB_DUMP_BEGIN: "0000"
      DB_CLEANUP_TIME: "10080"
      SPLIT_DB: FALSE
      CHECKSUM: SHA1
      COMPRESSION: GZ
      CONTAINER_ENABLE_MONITORING: FALSE
      DEBUG_MODE: FALSE
    entrypoint: "true"
    depends_on:
      gse-migration:
        condition: service_completed_successfully
    links:
      - gse-db
    networks:
      - default

  gse-fe:
    build:
      context: ../
      dockerfile: docker/website/Dockerfile
    image: 'gse/frontend:latest'
    container_name: gse-fe
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports: [ "7030:80" ]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on:
      gse-app:
        condition: service_healthy
    networks:
      - default


  gse-app:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    image: 'gse/backend:latest'
    container_name: gse-app
    volumes:
      - ./logs:/logs
    environment:
      WAIT_HOSTS: gse-db:3306
      LOGGING_CONFIG: classpath:logback.prod.xml
      SPRING_DATASOURCE_URL: jdbc:mysql://gse-db:3306/gse?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
      SPRING_FLYWAY_ENABLED: 'false'
      APP_CRAWL_ENABLED: 'false'
      APP_CRAWL_ANALYSIS_ENABLED: 'false'
      APP_CLEANUP_ENABLED: 'false'
      APP_CRAWL_TOKENS:
    ports: [ "48001:8080" ]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    healthcheck:
      test: curl --fail --silent localhost:8080/api || exit 1
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      gse-migration:
        condition: service_completed_successfully
    networks:
      - default

volumes:
  data:
    name: gse-data
  backup:
    name: gse-data-backups

networks:
  default:
    name: gse-network
