name: 'Prepare and create new tag'
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Semantic version string, format: /\d+\.\d+\.\d+/'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Validate inputs
        run: echo "${{ github.event.inputs.version }}" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.11.0
        with:
          checkout-persist-credentials: true
      - name: Update artifact version in POM
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
      - name: Create and push tag
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml'
          default_author: user_info
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          message: 'New release: ${{ github.event.inputs.version }}'
          tag: 'v${{ github.event.inputs.version }} --force'
          tag_push: '--force'
